### ISSUE TITLE
Non-Debian?

### ISSUE THREAD

**Issue by tianon** [debuerreotype/debuerreotype#1]
It'd be great to be able to use this to build at least consistent tarballs of Debian derivatives that aren't on snapshot.debian.org.

Perhaps one of the archive files has a useful timestamp that could be used for getting a semi-consistent/reproducible result?

**Comment by tianon** [comment]
For example, http://repo.steampowered.com/steamos/dists/brewmaster/Release has a decent-looking `Date` field, but I'm not sure how consistently that field will be updated for this repo or for other repos in the wild.

**Comment by tianon** [comment]
Example distros that might be worth considering:
- [Ubuntu](http://archive.ubuntu.com/ubuntu/)
- [Tanglu](http://archive.tanglu.org/tanglu/)
- [SteamOS](http://repo.steampowered.com/steamos/)
- [Linux Mint](http://packages.linuxmint.com/dists/)
- [Kali Linux](https://archive.kali.org/kali/)
- [Tails](https://time-based.snapshots.deb.tails.boum.org/debian/) [(has time-based archive snapshots!)](https://time-based.snapshots.deb.tails.boum.org/debian/dists/jessie/snapshots/)

**Comment by tianon** [comment]
Looks like APT itself does attach some value to that `Date` field in the `Release` file (https://github.com/Debian/apt/blob/7f18715769a93da7a99438f6de4e2533ac8c7ed8/test/integration/test-releasefile-date-older#L18), so perhaps that's a safe one to be using (if/when it exists). :sweat_smile:

**Comment by tianon** [comment]
Concrete scripts that need some kind of change to support this:

- `debuerreotype-init`
- `debuerreotype-gen-sources-list`

**Comment by DarkGigaByte** [comment]
Another distro that might be worth considering is [Devuan](https://files.devuan.org/). ;)

**Comment by tianon** [comment]
Here's the usage I'm currently imagining:
```console
$ debuerreotype-init --non-debian target-dir suite mirror [script]
```

Which then scrapes the given `mirror` for a `Date` value to use as epoch.  Possibly even noting in `target-dir` that we were non-Debian.

As for `debuerreotype-gen-sources-list`, I'm not sure I want to add support to that for any other distros -- that might be an exercise left to the user.  Still on the fence.  On the one hand, getting `sources.list` right for Ubuntu is [a challenge sometimes](https://bugs.launchpad.net/bugs/1711735), but on the other hand, that's extra complexity in the script which will be used very rarely.

**Comment by tianon** [comment]
The building blocks which should make this possible are now up over in https://github.com/debuerreotype/debuerreotype/pull/19. :+1:
