### ISSUE TITLE
Use of apt-cacher-ng

### ISSUE THREAD

**Issue by n-rodriguez** [debuerreotype/debuerreotype#113]
Hi there!

It doesn't seem possible right now to use an apt cache like apt-cacher-ng when running `debuerreotype-init`.

It would be really helpful to save some bandwith :)

Do you think it's feasible?

Thank you!

**Comment by n-rodriguez** [comment]
`export http_proxy=http://proxy`

**Comment by tianon** [comment]
FWIW, I hijack outgoing DNS requests and transparently hijack the hostnames instead 👍
