### ISSUE TITLE
Newby question

### ISSUE THREAD

**Issue by GOOD-Stuff** [debuerreotype/debuerreotype#132]
Hi! 
I perhaps wrong get point of this repository, if so, please correct me. 
Does this repo about building Debian rootfs? 
Does if yes, can i build it for armv7?

**Comment by tianon** [comment]
If you just want a Debian rootfs for armv7, I'd suggest using either `debootstrap` or `mmdebstrap`.

(This tool is specifically designed for building the specific rootfs tarballs for https://hub.docker.com/_/debian in a reproducible way.)
