### ISSUE TITLE
Q: what’s the actual Docker official-images use?

### ISSUE THREAD

**Issue by ecki** [debuerreotype/debuerreotype#156]
Where does the actual job for the official-images in docker hub run (GitHub workflow?), can we see the console log for those runs? And which parameters/steps (aka script) is used. Is this the example/debian-all.sh?

**Comment by yosifkit** [comment]
The Jenkins pipelines are defined over [here](https://github.com/docker-library/oi-janky-groovy/tree/15c7fac46d2bd7ca728c7e84bd43d1873c449212/tianon/debuerreotype). And the resulting Dockerfiles + rootfs tar files are all committed to https://github.com/debuerreotype/docker-debian-artifacts.

You can see the jobs in the Docker Official Images Jenkins instance: https://doi-janky.infosiftr.net/job/tianon/job/debuerreotype/

**Comment by ecki** [comment]
Thanks a lot for responding.

It is a quiet complex mashup for such an important infrastructure piece. Since it already depends heavily on GitHub, maybe a workflow would simplify it a bit?

**Comment by tianon** [comment]
GitHub actions doesn't support nearly enough CPU architectures, unfortunately.

**Comment by ecki** [comment]
> GitHub actions doesn't support nearly enough CPU architectures, unfortunately.

ah yes, good point, the GH runners for self hosting seems not to be too portable: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners
