### ISSUE TITLE
`libssl` is missing in tag "bookworm"

### ISSUE THREAD

**Issue by micl2e2** [debuerreotype/debuerreotype#159]
While the "bullseye" oci image ships with `libssl1.1` by default, it is not included in "bookworm" tag by default (`libssl3` there), neither as its [rootfs](https://doi-janky.infosiftr.net/job/tianon/job/debuerreotype/job/amd64/lastSuccessfulBuild/artifact/bookworm). 

Additionally, for "bookworm" cloud images or iso images, I found that `libssl3` is always included by default, is it a planned change for "bookworm" oci images?

bullseye tag: https://hub.docker.com/layers/library/debian/bullseye/images/sha256-7ac88cb3b95d347e89126a46696374fab97153b63d25995a5c6e75b5e98a0c79

bookworm tag: https://hub.docker.com/layers/library/debian/bookworm/images/sha256-9008de19fcf0f476fd2e6b43e16c33332afac4e9d7b95d8ae032e5fb4dead37a

**Comment by tianon** [comment]
I think this is going to be due to previous versions of APT linking against `libssl` and newer versions do not.  Generally, the project does not mark library packages as directly "essential", but they'll sometimes be called "transitively essential" (meaning they're in the dependency tree for an essential package), and this is the reason it was included previously.

I'm other words, it wasn't included or excluded explicitly, and generally won't be.  If you need it in your images, I would suggest installing it explicitly in them.

**Comment by micl2e2** [comment]
Make sense, thanks! @tianon

**Comment by tianon** [comment]
Now that I'm at a computer, I see that I got the details wrong (APT didn't link against `libssl1.1` directly in bullseye), but the general details were correct.  In this case, it's something (libpam, I think?) liking against Kerberos libraries (that then link against `libssl1.1`). :+1:

**Comment by micl2e2** [comment]
For the record,  on 11, this is caused by an indirect dependency for `libssl` by `libkrb5-3`, which is a dependency by  `libgssapi-krb5-2`, and then by `libtirpc3`, and then by `libpam-modules`. However on 12, it seems package `libpam-modules` drops the aforementioned dependencies, but this might only be true for packaging-level, because its [source](https://github.com/linux-pam/linux-pam/tree/v1.5.3) looks like still depending on `libtirpc` and `libnsl`.

For `libpam-modules`, its dependencies are 
```sh
# 11
Package: libpam-modules
Version: 1.4.0-9+deb11u1
Pre-Depends: libaudit1 (>= 1:2.2.1), libc6 (>= 2.27), libcrypt1 (>= 1:4.3.0), libdb5.3, libnsl2 (>= 1.0), libpam0g (>= 1.3.2),
 libselinux1 (>= 3.1~), libtirpc3 (>= 1.0.2), debconf (>= 0.5) | debconf-2.0, libpam-modules-bin (= 1.4.0-9+deb11u1)

# 12
Package: libpam-modules
Version: 1.5.2-6
Pre-Depends: libaudit1 (>= 1:2.2.1), libc6 (>= 2.34), libcrypt1 (>= 1:4.3.0), libdb5.3, libpam0g (>= 1.4.1), libselinux1 (>= 3.1~), debconf (>= 0.5) | debconf-2.0, libpam-modules-bin (= 1.5.2-6)

```
