### ISSUE TITLE
Trying to access `/etc/hostname` in Dockerfile yields `debuerreotype`

### ISSUE THREAD

**Issue by queirozfcom** [debuerreotype/debuerreotype#160]
Hi. I'm trying to retrieve the `hostname` from within the container (using `python:3.9-slim` base).

If I **ssh** into a running container, both the `HOSTNAME` env-var and the contents of `/etc/hostname` yield the correct values.

**However**, If I try to read `/etc/hostname` from within the `Dockerfile` I get `debuerreotype`, which I suppose is the default value because of [this](https://github.com/debuerreotype/debuerreotype/blob/master/docker-run.sh#L50)

How can I access the correct HOSTNAME during container start? I will try a hacky `time.sleep(3)` to see if the hostname is updated after some time.

**Comment by tianon** [comment]
Sorry! I'm hoping you closed this because you figured out what was going wrong?

I was going to ask how you're accessing `/etc/hostname` in your `Dockerfile` (since both Docker and BuildKit should be mounting over the top of any file from the image there), but I lost track of the email. :see_no_evil:

**Comment by queirozfcom** [comment]
> Sorry! I'm hoping you closed this because you figured out what was going wrong?
> 
> I was going to ask how you're accessing `/etc/hostname` in your `Dockerfile` (since both Docker and BuildKit should be mounting over the top of any file from the image there), but I lost track of the email. 🙈

Oh what a coincidence I had just closed it.

I was confused between code that runs at **image build time** and code that runs at **container run time**.

I even answered [my own question on SO](https://stackoverflow.com/a/77026800/436721)

Either way, thanks for following up on this :saluting_face:
