### ISSUE TITLE
copyright file getting whacked by slimify

### ISSUE THREAD

**Issue by draeath** [debuerreotype/debuerreotype#23]
I was experimenting with docker and was running a diff between stretch and stretch-slim, and I noticed that at least one copyright file was getting removed, even though it seems to be contrary to your intent. This file specifically was being removed: `/usr/share/doc/libmnl0/copyright` - I did see a handful of others.

I found this with the following command:
```
diff -u <(docker run --rm debian:stretch      bash -c 'find / -xdev -type f | sort') \
        <(docker run --rm debian:stretch-slim bash -c 'find / -xdev -type f | sort')
```

I apologize if this is intended behavior.

**Comment by yosifkit** [comment]
That is from a package that is not installed in slim images since it doesn't have `ip` or `ping`.

**Comment by draeath** [comment]
That... would actually make a lot of sense. Sorry!
