### ISSUE TITLE
repository errors - did layout change on snapshot.debian.org?

### ISSUE THREAD

**Issue by silhouette** [debuerreotype/debuerreotype#27]
Since this year our builds with debuerreotype fail, as some repositories seem to have changed on snapshot.debian.org.

For instance this fails now:

debuerreotype-apt-get output/20180109 update -qq
W: The repository 'http://snapshot.debian.org/archive/debian/20180109T000000Z stretch-updates Release' does not have a Release file.
E: Failed to fetch http://snapshot.debian.org/archive/debian-security/20180109T000000Z/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 185.17.185.185 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

With build-all.sh we get similar errors:

wget -O output/20180109/amd64/unstable/Release.gpg http://snapshot.debian.org/archive/debian/20180109T000000Z/dists/unstable/Release.gpg
--2018-01-09 13:02:56--  http://snapshot.debian.org/archive/debian/20180109T000000Z/dists/unstable/Release.gpg
Resolving snapshot.debian.org (snapshot.debian.org)... 185.17.185.185, 2001:1af8:4020:b030:deb::185
Connecting to snapshot.debian.org (snapshot.debian.org)|185.17.185.185|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-09 13:02:57 ERROR 404: Not Found.

**Comment by tianon** [comment]
The `Release.gpg` file shows up in http://snapshot.debian.org/archive/debian/20180108T153637Z/dists/unstable/, but clicking it results in a 404, so this must be some kind of issue with snapshot.debian.org. :confused:

**Comment by yosifkit** [comment]
`Release.gpg` now downloads fine for me.  It is working for you now?

**Comment by tianon** [comment]
Nice yeah, appears to be fixed! :+1:

**Comment by silhouette** [comment]
Yes, works fine now, thanks for investigating!

**Comment by tianon** [comment]
A little extra detail on this after talking to DSA: the hosts which power snapshot.debian.org are out of storage space, which is what's causing the intermittent 404s. :disappointed:

They've also confirmed that they're aware of the problem, and working on it.

**Comment by tianon** [comment]
From what I can see, this has been corrected! :smile: :+1: :heart:

(The affected hosts no longer show 100% usage on their drives in DSA's Munin instance.)
