### ISSUE TITLE
Possible to source packages from an iso image or a local package repository?

### ISSUE THREAD

**Issue by arrisde** [debuerreotype/debuerreotype#33]
Is it possible to use debuerreotype to create docker images from a (customized) Debian installer iso or a local package mirror? I understand reproducibility would always be given in this case, but it would still be useful to create a base image akin to the official Debian images but based on a custom, audited package source. Any pointers would be appreciated. 
(Apologies for opening an issue about this, I could not find a more appropriate channel for questions)

**Comment by tianon** [comment]
If it's something debootstrap itself can use, then absolutely -- you'll probably have to use https://github.com/debuerreotype/debuerreotype/pull/19 (`--non-debian`) to switch from using snapshot.debian.org to your local mirror instead, but it should be doable.

**Comment by tianon** [comment]
Closing since there's nothing I'm aware of here that's actionable. 👍
