### ISSUE TITLE
Unused variable in raspbian.sh script

### ISSUE THREAD

**Issue by cailloumajor** [debuerreotype/debuerreotype#45]
Hello. First of all, thanks for this great tool !

The variable below is initialized but never used in the rest of the script. Seems to be a relic of another script.
https://github.com/debuerreotype/debuerreotype/blob/8f32a3f4b96e38d1c8fc7732c5222b0b48a73c7c/raspbian.sh#L71

**Comment by tianon** [comment]
Yep, good catch -- the `raspbian.sh` script is cloned from `build.sh` mostly as an example.

If you do a diff between them, it should be slightly more clear that `raspbian.sh` is just `build.sh` with sections that don't apply removed (which doesn't necessarily apply to removing variables that were shared among all those sections, such as the one you've discovered).
