### ISSUE TITLE
/tmp mounted as a volume in raspbian.sh

### ISSUE THREAD

**Issue by cailloumajor** [debuerreotype/debuerreotype#46]
The script `raspbian.sh` mounts `/tmp` as a volume in the container :
https://github.com/debuerreotype/debuerreotype/blob/8f32a3f4b96e38d1c8fc7732c5222b0b48a73c7c/raspbian.sh#L53-L60
All the other scripts (`build.sh`, `steamos.sh` and `ubuntu.sh`) mount it as a tmpfs :
https://github.com/debuerreotype/debuerreotype/blob/06573aa1801902819c1f6eb5f432f75760f5642c/build.sh#L72-L83
What is the explanation for this difference ?

**Comment by tianon** [comment]
It was probably something as simple as the fact that the machine I was building/testing `raspbian.sh` on didn't have enough RAM to build the full rootfs and tarballs in a `tmpfs`. :sweat_smile:

**Comment by cailloumajor** [comment]
:+1: :laughing:
