### ISSUE TITLE
raspian.sh seems to be broken

### ISSUE THREAD

**Issue by rmoriz** [debuerreotype/debuerreotype#52]
I'm trying to get a raspbian rootfs built (and build a sane raspbian base image which I coudn't find)

However I'm getting the following errors with the current master head 99259e6:

```shell
$ ./raspbian.sh  output stretch
…
I: Extracting util-linux...
I: Extracting xz-utils...
I: Extracting zlib1g...
W: Failure trying to run: chroot /tmp/rootfs dpkg-deb -f /var/cache/apt/archives/dpkg_1.18.25_armhf.deb Version
W: See /tmp/rootfs/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot /tmp/rootfs mount -t proc proc /proc
W: See /tmp/rootfs/debootstrap/debootstrap.log for details

error: 'debootstrap' failed!

  Full command:

    debootstrap --force-check-gpg --variant=minbase --merged-usr --keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg --arch=armhf stretch rootfs http://archive.raspbian.org/raspbian

  Logs:

gpgv: Signature made Wed Feb 13 16:55:36 2019 UTC
gpgv:                using RSA key 9165938D90FDDD2E
gpgv: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
chroot: failed to run command 'dpkg-deb': No such file or directory
chroot: failed to run command 'mount': No such file or directory

tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

I'm running this script on an ubuntu 18.04.01 and docker 18.09.1

Thanks

**Comment by rmoriz** [comment]
I think it was my fault:

1. attempt: I tried `raspbian.sh` on device (Raspberry Pi Zero) but it failed early with `The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends 		debootstrap 		wget ca-certificates 		xz-utils 		gnupg dirmngr 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 139` probably caused by docker picking the wrong debian base image (debian/stretch-slim for `arm` which is debian's `armhf` which seems not to be identical to Raspbian's`armhf`. Raspbian's `armhf` works on older ARM devices but Debian requires to use their `armel` arch for it)

2. I tried it with a working qemu setup on my amd64 machine but without the qemu binary inside the container, i'm getting the `"Failure trying to run: chroot /tmp/rootfs dpkg-deb -f"` and can manually reproduce it.

I guess I'll get a Raspberry Model 3 B and build the image on that device?

**Comment by tianon** [comment]
Yeah, that may or may not work -- you could also probably try using `FROM tianon/raspbian:stretch-slim` (or any other existing Raspbian Stretch image).

I'm building on a system with `binfmt`'s "fix binary" support enabled so that I don't have to copy in the QEMU binaries (https://www.kernel.org/doc/html/v4.18/admin-guide/binfmt-misc.html), which makes things a little easier to test/use.

You might also have luck swapping `debootstrap` with `qemu-debootstrap` (see the `--debootstrap` flag for `debuerreotype-init`) which does the binary copying to make `debootstrap` work without "fix binary" on `binfmt`.

**Comment by tianon** [comment]
(Closing, since this does appear to be working, although is a bit quirky to get running properly.)

**Comment by rmoriz** [comment]
Thanks for the hint. Didn't know about the `F` flag 👍 

It works now on device (when using the arm32v5 image) and when using qemu-arm-static on x86_64/amd64 using `binfmt` with the `F` flag.

**Comment by tianon** [comment]
Yeah! The `F` flag is some serious black magic. 😅
