### ISSUE TITLE
running it whithout being root

### ISSUE THREAD

**Issue by meskio** [debuerreotype/debuerreotype#66]
I'm trying to use debuerreotype without being root. I see debootstrap and chroot works fine with fakechroot+fakeroot, so I tried the same. But I got an error on the debootstrap part of the init:
```
$ PATH=$PATH:/usr/sbin fakechroot fakeroot /usr/sbin/debuerreotype-init rootfs stable `date +%FT%T`
[...]
W: Failure trying to run: chroot "/tmp/rootfs7" mount -t proc proc /proc
W: See /tmp/rootfs7/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot "/tmp/rootfs7" mount -t sysfs sysfs /sys
W: See /tmp/rootfs7/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot "/tmp/rootfs7" /sbin/ldconfig
W: See /tmp/rootfs7/debootstrap/debootstrap.log for details

error: 'debootstrap' failed!

  Full command:

    debootstrap --force-check-gpg --variant=minbase --merged-usr stable rootfs http://snapshot.debian.org/archive/debian/20190712T094924Z
[...]
```

But if I tried to execute the same debootstrap command independetly of debuerreotype it works fine:
```
$ fakechroot fakeroot debootstrap --force-check-gpg --variant=minbase --merged-usr stable rootfs http://snapshot.debian.org/archive/debian/20190712T094924Z
```

I tried to create my fake debootstrap binary:
```sh
#!/bin/sh

fakechroot fakeroot debootstrap $@
```
And then run debuerreotype, and this works fine until debeurretype needs to use unshare:
```
$ /usr/sbin/debuerreotype-init --debootstrap='fakedebootstrap' rootfs stable `date +%FT%T`
[...]
I: Unpacking the base system...
I: Base system installed successfully.
unshare: unshare failed: Operation not permitted
```
Weird, somehow fake\*root commands are not "passing" the environment well to debootstrap. I tried to add fake\*root commands also to the last debuerrotype-init, but fake*root commands don't like to nest and fail.

Any ideas?

**Comment by tianon** [comment]
Hmm, we use `unshare` so we can `mount --rbind` all of `/proc`, `/sys`, `/dev`, and `/etc/resolv.conf` so things inside the `chroot` generally "just work" -- how would one normally handle those in a `fakechroot`?

**Comment by meskio** [comment]
I just started playing with fakechroot, and I didn't even know about unshare before yesterday. Not sure if I have any good ideas. I'll see if I find something.

My first problem is not so much unshare, but the weird behavior with fakechroot not working globally for the whole invocation.

Any way, thanks, I'm just dumping here my experiments, as I'm kind of blocked without more ideas on how to continue.

**Comment by meskio** [comment]
After some more testing I give up on the idea of running it as non-root. I was trying to build docker base images without being root, but I don't think it will work (or not easily).

Thanks and sorry for the noise.
