### ISSUE TITLE
Building from an ISO image

### ISSUE THREAD

**Issue by rico-chet** [debuerreotype/debuerreotype#73]
Since #33 is closed and I cannot reopen it, opening a new one (note: I am not the author of the original issue).

The goal I am trying to achieve is creating a build environment for a product which has a lifetime of ten years. The environment should be independent of any online sources (which can go offline) and we need an option to install additional build tools inside the environment as the product evolves, without hassle.

My current approach is to download a double-layer Blu-ray ISO image of _buster_ and to utilize `debuerreotype` to create a root file system which can then be used in a chroot or a docker image.

So I run an HTTP server in the mounted ISO's root directory and point `debuerreotype-init --non-debian` there and... it fails ;-). Specifically, there is no `Release.gpg` file in the ISO image and since `--force-check-gpg` is [set for `debootstrap` unconditionally](https://github.com/debuerreotype/debuerreotype/blob/0.10/scripts/debuerreotype-init#L81), it fails. When I patch the parameter to `--no-check-gpg`, it works `\o/`. I was able to import the image to docker and use `apt` in it (docker needs the `--net=host` parameter to make the localhost repo available in the container).

After this, I need to provide different parameters to `apt` to make it work with the unsigned repository, or (better) set `[trusted=yes]` on that repo in the `sources.list`.

Thus, we have actionable items now:

- [ ] Make GPG signature check optional
- [x] Mark the local repository trusted

Note that for testing, I use the smaller [CD image](https://cdimage.debian.org/mirror/cdimage/archive/10.0.0/amd64/iso-cd/debian-10.0.0-amd64-xfce-CD-1.iso).

**Comment by tianon** [comment]
Ouch -- IMO it's weird that the ISOs don't include `Release.gpg` files, but I guess it's likely due to them being a partial mirror and thus not being able to include the "official" signatures verbatim and built via a completely separate process and thus not able to securely share the real archive signing key.

For that part of the problem, I'm tentatively :+1: on including a `--no-check-gpg` flag to `debuerreotype-init` (which would then get passed to `debootstrap`).

For the second half (`sources.list` generation), we only explicitly generate `sources.list` contents for real Debian builds (via the purpose-built `debuerreotype-debian-sources-list` script), so I'm still not convinced there's anything for us to do there -- that's more an exercise for the thing invoking our scripts to clean up `sources.list` after `debootstrap` does whatever it is it's going to do (because otherwise, the default `sources.list` is entirely generated by debootstrap, not debuerreotype).

**Comment by tianon** [comment]
It needs some testing before it's made into a PR, but here's the approach I've got in mind for this new behavior:

```diff
diff --git a/scripts/debuerreotype-init b/scripts/debuerreotype-init
index 07066f3..73aee77 100755
--- a/scripts/debuerreotype-init
+++ b/scripts/debuerreotype-init
@@ -8,6 +8,7 @@ source "$thisDir/.constants.sh" \
 	--flags 'debootstrap-script:' \
 	--flags 'keyring:,arch:,include:,exclude:' \
 	--flags 'merged-usr,no-merged-usr' \
+	--flags 'check-gpg,no-check-gpg' \
 	-- \
 	'<target-dir> <suite> <timestamp>' \
 	'rootfs stretch 2017-05-08T00:00:00Z
@@ -27,6 +28,7 @@ arch=
 include=
 exclude=
 noMergedUsr=
+noCheckGpg=
 while true; do
 	flag="$1"; shift
 	dgetopt-case "$flag"
@@ -43,6 +45,8 @@ while true; do
 		--exclude) exclude="${exclude:+$exclude,}$1"; shift ;;
 		--merged-usr)    noMergedUsr=  ;;
 		--no-merged-usr) noMergedUsr=1 ;;
+		--check-gpg)    noCheckGpg=  ;;
+		--no-check-gpg) noCheckGpg=1 ;;
 		--) break ;;
 		*) eusage "unknown flag '$flag'" ;;
 	esac
@@ -89,9 +93,13 @@ if [ -z "$nonDebian" ]; then
 	fi
 fi
 
-debootstrapArgs=(
-	--force-check-gpg
-)
+debootstrapArgs=()
+
+if [ -z "$noCheckGpg" ]; then
+	debootstrapArgs+=( --force-check-gpg )
+else
+	debootstrapArgs+=( --no-check-gpg )
+fi
 
 minbaseSupported="$(
 	scriptFile="$(
```

**Comment by rico-chet** [comment]
After backporting the patch to 0.4 (the Ubuntu 18.04 VM I use had this version installed): https://github.com/rico-chet/debuerreotype/commit/4f9af7d40045bc92d035aa431908af7470efc24e, this worked:

```console
$ wget -q https://cdimage.debian.org/mirror/cdimage/archive/10.0.0/amd64/iso-cd/debian-10.0.0-amd64-xfce-CD-1.iso
$ mkdir iso-mnt
$ sudo mount -o ro debian-10.0.0-amd64-xfce-CD-1.iso iso-mnt
$ (cd iso-mnt && sudo python3 -m http.server 80 2>/dev/null 1>&2) &
[1] 12345
$ sudo debuerreotype-init --non-debian --no-check-gpg rootfs buster http://localhost:80
[snip]
I: Base system installed successfully.
$ sudo sed -i 's|\(deb\) \(http://localhost:80 \)|\1 [trusted=yes] \2|' rootfs/etc/apt/sources.list
$ sudo debuerreotype-minimizing-config rootfs
$ sudo debuerreotype-fixup rootfs
$ sudo debuerreotype-tar rootfs - | docker import - buildenv:10.0
sha256:ee836b35a4f919ec32cb6661d0c73874c47770f43fe2efdd2e1b33c22ea2501b
$ docker run --interactive --net=host --rm --tty buildenv:10.0 bash
root@ubuntu:/# apt update
Ign:1 http://localhost:80 buster InRelease
Get:2 http://localhost:80 buster Release [31.7 kB]
Ign:3 http://localhost:80 buster Release.gpg
Ign:4 http://localhost:80 buster/main amd64 Packages
Get:4 http://localhost:80 buster/main amd64 Packages [214 kB]
Fetched 246 kB in 0s (6553 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@ubuntu:/# apt install less
Reading package lists... Done
Building dependency tree
Reading state information... Done                                                                                                                 The following NEW packages will be installed:
  less
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 129 kB of archives.
After this operation, 288 kB of additional disk space will be used.                                                                               Get:1 http://localhost:80 buster/main amd64 less amd64 487-0.1+b1 [129 kB]
Fetched 129 kB in 0s (0 B/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package less.
(Reading database ... 6459 files and directories currently installed.)
Preparing to unpack .../less_487-0.1+b1_amd64.deb ...
Unpacking less (487-0.1+b1) ...
Setting up less (487-0.1+b1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
root@ubuntu:/# exit
```

Cleanup:
```console
$ fg
( cd iso-mnt && sudo python3 -m http.server 80 2> /dev/null 1>&2 )
Ctrl+C
$ docker image rm buildenv:10.0
Untagged: buildenv:10.0
Deleted: sha256:ee836b35a4f919ec32cb6661d0c73874c47770f43fe2efdd2e1b33c22ea2501b
$ sudo umount iso-mnt
$ sudo rm -fr rootfs iso-mnt debian-10.0.0-amd64-xfce-CD-1.iso
```
