### ISSUE TITLE
Remove apt cache and fetched list

### ISSUE THREAD

**Issue by cranebytes** [debuerreotype/debuerreotype#74]
I was wondering why my images are so fat and I found out that `/var/lib/apt` and `/var/cache/apt` are not emptied during the build process.
I think removing those files should be part of this scripts because we all want smaller images.

IMHO this should be done right before tar'ing the image.
So I could build this in into `debuerreotype-tar` or create a new helper script like `.cleanup-apt`.

Any suggestions on this?

**Comment by tianon** [comment]
I'm honestly confused how you managed to get a tarball with `/var/lib/apt` and/or `/var/cache/apt` having fat contents:

https://github.com/debuerreotype/debuerreotype/blob/c38deb8b0be02f4cfdef014673a60cf8f89a5a7a/scripts/debuerreotype-tar#L34-L54

https://github.com/debuerreotype/debuerreotype/blob/c38deb8b0be02f4cfdef014673a60cf8f89a5a7a/scripts/.tar-exclude#L9-L20

(We already exclude them as aggressively as possible based on `apt` version as part of `debuerreotype-tar`.)

**Comment by cranebytes** [comment]
I think this is a hard case of layer 8 and I will close this in shame... :)
