### ISSUE TITLE
Remove timestamps from /etc/shadow

### ISSUE THREAD

**Issue by cranebytes** [debuerreotype/debuerreotype#85]
`/etc/shadow` has some columns with timestamps in it. In our case it is the third column which makes some trouble.

If we have two builds, one from day A and one from day B. Even if there are no changes in the packages there is still a change on the timestamps and resulting in a kinda "false" positive diff.

It would be greate if there would be an option to remove those timestamps on the debuerreotype-init script. Something like `--patch-shadow`.

Right now I'm doing it like here:

```
awk '{$3 = "0"}1' FS=':' OFS=':' /root/rootfs/etc/shadow > /root/rootfs/etc/shadow.tmp
mv /root/rootfs/etc/shadow.tmp /root/rootfs/etc/shadow
rm /root/rootfs/etec/shadow-
```

**Comment by tianon** [comment]
I think the idea of having "no changes" lead to "no diff" is an interesting one, but it's not really the goal of `debuerreotype` (which is more about transparency / reproducibility).

Hopefully this issue (plus #84) will serve as a good starting point for users who want that, however!
(it shouldn't be *too* difficult to go from the output of a standard `debuerreotype` build to what you're after, as you've shown)
